version: "3"
services:
    service:
        build: ./service
        container_name: infrastructure-automation-demo-service
    static:
        build: ./static
        container_name: infrastructure-automation-demo-static
    reverse-proxy:
        build: ./reverse-proxy
        ports:
            - "18092:18092"
        container_name: infrastructure-automation-demo-reverse-proxy
