version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - /var/jenkins_home:/var/jenkins_home
    ports:
      - "18080:8080"
      - "50000:50000"
    restart: always
    container_name: jenkins
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JAVA_OPTS="-Djava.util.logging.config.file=/var/jenkins_home/log.properties"
